position:
  default: bottom
  type: enum
  choices:
  - top
  - bottom
  - top-left
  - top-right
  - bottom-left
  - bottom-right
  description: 
    en: 'The position of the cookie banner relative to the page'
main_text:
  type: string
  default: "This website uses cookies to ensure you get the best experience on our website."
topic_ids:
  default: ""
  type: list
  description: "Ads will only show for these topics"
tags:
  default: ""
  type: list
  description: "Ads will only show for these tags"